name: podcast_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  animate_do: ^2.1.0
  bloc: ^8.0.2
  connectivity_plus: ^2.2.0
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  iconsax: ^0.0.8
  intl: ^0.17.0
  oxidized: ^5.1.0
  get_storage: ^2.0.3
  audioplayers: ^0.20.1
  animations: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
